# Generated by Django 4.2.16 on 2024-09-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
